// const socket = {
//            _events: [Object: null prototype] {},
//            _eventsCount: 0,
//            _maxListeners: undefined,
//            nsp: Namespace {
//              _events: [Object: null prototype] { connection: [Function] },
//              _eventsCount: 1,
//              _maxListeners: undefined,
//              sockets: Map { 'i5_n7zztjpRuwOECAAAB' => [Circular] },
//              _fns: [],
//              _rooms: Set {},
//              _flags: {},
//              _ids: 0,
//              server: Server {
//                _events: [Object: null prototype] {},
//                _eventsCount: 0,
//                _maxListeners: undefined,
//                _nsps: [Map],
//                parentNsps: Map {},
//                _path: '/socket.io',
//                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
//                _connectTimeout: 45000,
//                _serveClient: true,
//                _parser: [Object],
//                encoder: Encoder {},
//                _adapter: [Function: Adapter],
//                sockets: [Circular],
//                opts: [Object],
//                eio: [Server],
//                httpServer: [Server],
//                engine: [Server],
//                [Symbol(kCapture)]: false
//              },
//              name: '/',
//              adapter: Adapter {
//                _events: [Object: null prototype] {},
//                _eventsCount: 0,
//                _maxListeners: undefined,
//                nsp: [Circular],
//                rooms: [Map],
//                sids: [Map],
//                encoder: Encoder {},
//                [Symbol(kCapture)]: false
//              },
//              [Symbol(kCapture)]: false
//            client: Client {
//              sockets: Map { 'i5_n7zztjpRuwOECAAAB' => [Circular] },
//              nsps: Map { '/' => [Circular] },
//              server: Server {
//                _events: [Object: null prototype] {},
//                _eventsCount: 0,
//                _maxListeners: undefined,
//                _nsps: [Map],
//                parentNsps: Map {},
//                _path: '/socket.io',
//                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
//                _connectTimeout: 45000,
//                _serveClient: true,
//                _parser: [Object],
//                encoder: Encoder {},
//                _adapter: [Function: Adapter],
//                sockets: [Namespace],
//                opts: [Object],
//                eio: [Server],
//                httpServer: [Server],
//                engine: [Server],
//                [Symbol(kCapture)]: false
//              },
//              conn: Socket {
//                _events: [Object: null prototype],
//                _eventsCount: 3,
//                _maxListeners: undefined,
//                id: 'GlA8c_BWwl-59zdIAAAA',
//                server: [Server],
//                upgrading: true,
//                upgraded: false,
//                readyState: 'open',
//                writeBuffer: [Array],
//                packetsFn: [],
//                sentCallbackFn: [],
//                cleanupFn: [Array],
//                request: [IncomingMessage],
//                remoteAddress: '::1',
//                checkIntervalTimer: null,
//                upgradeTimeoutTimer: Timeout {
//                  _idleTimeout: 10000,
//                  _idlePrev: [TimersList],
//                  _idleNext: [Timeout],
//                  _idleStart: 28162,
//                  _onTimeout: [Function],
//                  _timerArgs: undefined,
//                  _repeat: null,
//                  _destroyed: false,
//                  [Symbol(refed)]: true,
//                  [Symbol(asyncId)]: 254,
//                  [Symbol(triggerId)]: 249
//                },
//                pingTimeoutTimer: Timeout {
//                  _idleTimeout: 30000,
//                  _idlePrev: [TimersList],
//                  _idleNext: [TimersList],
//                  _idleStart: 28163,
//                  _onTimeout: [Function],
//                  _timerArgs: undefined,
//                  _repeat: null,
//                  _destroyed: false,
//                  [Symbol(refed)]: true,
//                  [Symbol(asyncId)]: 258,
//                  [Symbol(triggerId)]: 257
//                },
//                pingIntervalTimer: Timeout {
//                  _idleTimeout: 25000,
//                  _idlePrev: [TimersList],
//                  _idleNext: [TimersList],
//                  _idleStart: 28152,
//                  _onTimeout: [Function],
//                  _timerArgs: undefined,
//                  _repeat: null,
//                  _destroyed: false,
//                  [Symbol(refed)]: true,
//                  [Symbol(asyncId)]: 237,
//                  [Symbol(triggerId)]: 0
//                },
//                transport: [Polling],
//                [Symbol(kCapture)]: false
//              },
//              encoder: Encoder {},
//              decoder: Decoder { _callbacks: [Object] },
//              id: 'GlA8c_BWwl-59zdIAAAA',
//              onclose: [Function: bound onclose],
//              ondata: [Function: bound ondata],
//              onerror: [Function: bound onerror],
//              ondecoded: [Function: bound ondecoded],
//              connectTimeout: null
//            },
//            acks: Map {},
//            fns: [],
//            flags: {},
//            _rooms: Set {},

//            server: Server {
//              _events: [Object: null prototype] {},
//              _eventsCount: 0,
//              _maxListeners: undefined,
//              _nsps: Map { '/' => [Namespace] },
//              parentNsps: Map {},
//              _path: '/socket.io',
//              clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
//              _connectTimeout: 45000,
//              _serveClient: true,
//              _parser: {
//                protocol: 5,
//                PacketType: [Object],
//                Encoder: [Function: Encoder],
//                Decoder: [Function: Decoder]
//              },
//              encoder: Encoder {},
//              _adapter: [Function: Adapter],
//              sockets: Namespace {
//                _events: [Object: null prototype],
//                _eventsCount: 1,
//                _maxListeners: undefined,
//                sockets: [Map],
//                _fns: [],
//                _rooms: Set {},
//                _flags: {},
//                _ids: 0,
//                server: [Circular],
//                name: '/',
//                adapter: [Adapter],
//                [Symbol(kCapture)]: false
//              },
//              opts: { cors: [Object] },
//              eio: Server {
//                _events: [Object: null prototype],
//                _eventsCount: 1,
//                _maxListeners: undefined,
//                clients: [Object],
//                clientsCount: 1,
//                opts: [Object],
//                corsMiddleware: [Function: corsMiddleware],
//                ws: [WebSocketServer],
//                [Symbol(kCapture)]: false
//              },
//              httpServer: Server {
//                insecureHTTPParser: undefined,
//                _events: [Object: null prototype],
//                _eventsCount: 5,
//                _maxListeners: undefined,
//                _connections: 2,
//                _handle: [TCP],
//                _usingWorkers: false,
//                _workers: [],
//                _unref: false,
//                allowHalfOpen: true,
//                pauseOnConnect: false,
//                httpAllowHalfOpen: false,
//                timeout: 120000,
//                keepAliveTimeout: 5000,
//                maxHeadersCount: null,
//                headersTimeout: 40000,
//                _connectionKey: '6::::5000',
//                [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//                [Symbol(ServerResponse)]: [Function: ServerResponse],
//                [Symbol(kCapture)]: false,
//                [Symbol(asyncId)]: 7
//              },
//              engine: Server {
//                _events: [Object: null prototype],
//                _eventsCount: 1,
//                _maxListeners: undefined,
//                clients: [Object],
//                clientsCount: 1,
//                opts: [Object],
//                corsMiddleware: [Function: corsMiddleware],
//                ws: [WebSocketServer],
//                [Symbol(kCapture)]: false
//              },
//              [Symbol(kCapture)]: false
//            },
//            adapter: Adapter {
//              _events: [Object: null prototype] {},
//              _eventsCount: 0,
//              _maxListeners: undefined,
//              nsp: Namespace {
//                _events: [Object: null prototype],
//                _eventsCount: 1,
//                _maxListeners: undefined,
//                sockets: [Map],
//                _fns: [],
//                _rooms: Set {},
//                _flags: {},
//                _ids: 0,
//                server: [Server],
//                name: '/',
//                adapter: [Circular],
//                [Symbol(kCapture)]: false
//              },
//              rooms: Map { 'i5_n7zztjpRuwOECAAAB' => [Set] },
//              sids: Map { 'i5_n7zztjpRuwOECAAAB' => [Set] },
//              encoder: Encoder {},
//              [Symbol(kCapture)]: false
//            },
//            id: 'i5_n7zztjpRuwOECAAAB',
//            connected: true,
//            disconnected: false,
//            handshake: {
//              headers: {
//                host: 'localhost:5000',
//                connection: 'keep-alive',
//                'sec-ch-ua': '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
//                accept: '*/*',
//                'sec-ch-ua-mobile': '?0',
//                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36',
//                origin: 'http://localhost:3000',
//                'sec-fetch-site': 'same-site',
//                'sec-fetch-mode': 'cors',
//                'sec-fetch-dest': 'empty',
//                referer: 'http://localhost:3000/',
//                'accept-encoding': 'gzip, deflate, br',
//                'accept-language': 'en-US,en;q=0.9'
//              },
//              time: 'Tue Dec 29 2020 17:58:51 GMT-0500 (Eastern Standard Time)',
//              address: '::1',
//              xdomain: true,
//              secure: false,
//              issued: 1609282731522,
//              url: '/socket.io/?EIO=4&transport=polling&t=NQmkRtm',
//              query: [Object: null prototype] {
//                EIO: '4',
//                transport: 'polling',
//                t: 'NQmkRtm'
//              },
//              auth: {}
//            },
//            [Symbol(kCapture)]: false
// }
